spring:
  datasource:
    url: jdbc:mariadb://172.16.191.102:3306/cms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mybatis:
    mapper-location: classpath:mapper/*Mapper.xml
    type-aliases-package: com.hsy.cms.better.bean.entity
  logging:
    level:
      com:
        hsy:
          cms:
            better:
              mapper: TRACE
