spring:
  datasource:
    url: jdbc:mariadb://172.16.191.102:3306/cms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mybatis:
    config-location: classpath:/mybatis-config.xml
  logging:
    level:
      org:
        springfremework:
          web: debug
        apache:
          ibatis: TRACE
      java:
        sql:
          Connection: DEBUG
          Statement: DEBUG
          PreparedStatement: DEBUG
  redis:
    database: 0
    sentinel:
      master: mymaster
      nodes: 192.168.216.157:26379,192.168.216.158:26380,192.168.216.159:26381
    timeout: 5000
    host: 192.168.216.157
    port: 6379
    password: 123456