INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000001, 'Angola', 0, 0, 'AO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000002, 'Afghanistan', 0, 0, 'AF');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000003, 'Albania', 0, 0, 'AL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000004, 'Algeria', 0, 0, 'DZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000005, 'Andorra', 0, 0, 'AD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000006, 'Anguilla', 0, 0, 'AI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000007, 'Antigua and Barbuda', 0, 0, 'AG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000008, 'Argentina', 0, 0, 'AR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000009, 'Armenia', 0, 0, 'AM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000010, 'Australia', 0, 0, 'AU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000011, 'Austria', 0, 0, 'AT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000012, 'Azerbaijan', 0, 0, 'AZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000013, 'Bahamas', 0, 0, 'BS');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000014, 'Bahrain', 0, 0, 'BH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000015, 'Bangladesh', 0, 0, 'BD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000016, 'Barbados', 0, 0, 'BB');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000017, 'Belarus', 0, 0, 'BY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000018, 'Belgium', 0, 0, 'BE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000019, 'Belize', 0, 0, 'BZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000020, 'Benin', 0, 0, 'BJ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000021, 'Bermuda Is.', 0, 0, 'BM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000022, 'Bolivia', 0, 0, 'BO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000023, 'Botswana', 0, 0, 'BW');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000024, 'Brazil', 0, 0, 'BR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000025, 'Brunei', 0, 0, 'BN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000026, 'Bulgaria', 0, 0, 'BG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000027, 'Burkina-faso', 0, 0, 'BF');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000028, 'Burma', 0, 0, 'MM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000029, 'Burundi', 0, 0, 'BI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000030, 'Cameroon', 0, 0, 'CM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000031, 'Canada', 0, 0, 'CA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000032, 'Central African Republic', 0, 0, 'CF');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000033, 'Chad', 0, 0, 'TD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000034, 'Chile', 0, 0, 'CL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000035, 'China', 0, 0, 'CN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000036, 'Colombia', 0, 0, 'CO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000037, 'Congo', 0, 0, 'CG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000038, 'Cook Is.', 0, 0, 'CK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000039, 'Costa Rica', 0, 0, 'CR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000040, 'Cuba', 0, 0, 'CU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000041, 'Cyprus', 0, 0, 'CY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000042, 'Czech Republic', 0, 0, 'CZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000043, 'Denmark', 0, 0, 'DK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000044, 'Djibouti', 0, 0, 'DJ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000045, 'Dominica Rep.', 0, 0, 'DO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000046, 'Ecuador', 0, 0, 'EC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000047, 'Egypt', 0, 0, 'EG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000048, 'EI Salvador', 0, 0, 'SV');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000049, 'Estonia', 0, 0, 'EE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000050, 'Ethiopia', 0, 0, 'ET');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000051, 'Fiji', 0, 0, 'FJ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000052, 'Finland', 0, 0, 'FI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000053, 'France', 0, 0, 'FR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000054, 'French Guiana', 0, 0, 'GF');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000055, 'Gabon', 0, 0, 'GA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000056, 'Gambia', 0, 0, 'GM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000057, 'Georgia', 0, 0, 'GE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000058, 'Germany', 0, 0, 'DE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000059, 'Ghana', 0, 0, 'GH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000060, 'Gibraltar', 0, 0, 'GI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000061, 'Greece', 0, 0, 'GR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000062, 'Grenada', 0, 0, 'GD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000063, 'Guam', 0, 0, 'GU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000064, 'Guatemala', 0, 0, 'GT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000065, 'Guinea', 0, 0, 'GN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000066, 'Guyana', 0, 0, 'GY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000067, 'Haiti', 0, 0, 'HT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000068, 'Honduras', 0, 0, 'HN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000069, 'Hongkong', 0, 0, 'HK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000070, 'Hungary', 0, 0, 'HU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000071, 'Iceland', 0, 0, 'IS');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000072, 'India', 0, 0, 'IN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000073, 'Indonesia', 0, 0, 'ID');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000074, 'Iran', 0, 0, 'IR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000075, 'Iraq', 0, 0, 'IQ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000076, 'Ireland', 0, 0, 'IE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000077, 'Israel', 0, 0, 'IL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000078, 'Italy', 0, 0, 'IT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000079, 'Jamaica', 0, 0, 'JM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000080, 'Japan', 0, 0, 'JP');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000081, 'Jordan', 0, 0, 'JO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000082, 'Kampuchea (Cambodia )', 0, 0, 'KH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000083, 'Kazakstan', 0, 0, 'KZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000084, 'Kenya', 0, 0, 'KE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000085, 'Korea', 0, 0, 'KR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000086, 'Kuwait', 0, 0, 'KW');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000087, 'Kyrgyzstan', 0, 0, 'KG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000088, 'Laos', 0, 0, 'LA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000089, 'Latvia', 0, 0, 'LV');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000090, 'Lebanon', 0, 0, 'LB');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000091, 'Lesotho', 0, 0, 'LS');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000092, 'Liberia', 0, 0, 'LR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000093, 'Libya', 0, 0, 'LY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000094, 'Liechtenstein', 0, 0, 'LI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000095, 'Lithuania', 0, 0, 'LT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000096, 'Luxembourg', 0, 0, 'LU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000097, 'Macao', 0, 0, 'MO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000098, 'Madagascar', 0, 0, 'MG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000099, 'Malawi', 0, 0, 'MW');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000100, 'Malaysia', 0, 0, 'MY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000101, 'Maldives', 0, 0, 'MV');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000102, 'Mali', 0, 0, 'ML');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000103, 'Malta', 0, 0, 'MT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000104, 'Mauritius', 0, 0, 'MU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000105, 'Mexico', 0, 0, 'MX');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000106, 'Moldova, Republic of', 0, 0, 'MD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000107, 'Monaco', 0, 0, 'MC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000108, 'Mongolia', 0, 0, 'MN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000109, 'Montserrat Is', 0, 0, 'MS');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000110, 'Morocco', 0, 0, 'MA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000111, 'Mozambique', 0, 0, 'MZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000112, 'Namibia', 0, 0, 'NA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000113, 'Nauru', 0, 0, 'NR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000114, 'Nepal', 0, 0, 'NP');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000115, 'Netherlands', 0, 0, 'NL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000116, 'New Zealand', 0, 0, 'NZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000117, 'Nicaragua', 0, 0, 'NI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000118, 'Niger', 0, 0, 'NE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000119, 'Nigeria', 0, 0, 'NG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000120, 'North Korea', 0, 0, 'KP');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000121, 'Norway', 0, 0, 'NO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000122, 'Oman', 0, 0, 'OM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000123, 'Pakistan', 0, 0, 'PK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000124, 'Panama', 0, 0, 'PA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000125, 'Papua New Cuinea', 0, 0, 'PG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000126, 'Paraguay', 0, 0, 'PY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000127, 'Peru', 0, 0, 'PE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000128, 'Philippines', 0, 0, 'PH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000129, 'Poland', 0, 0, 'PL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000130, 'French Polynesia', 0, 0, 'PF');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000131, 'Portugal', 0, 0, 'PT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000132, 'Puerto Rico', 0, 0, 'PR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000133, 'Qatar', 0, 0, 'QA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000134, 'Romania', 0, 0, 'RO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000135, 'Russia', 0, 0, 'RU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000136, 'Saint Lueia', 0, 0, 'LC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000137, 'Saint Vincent', 0, 0, 'VC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000138, 'San Marino', 0, 0, 'SM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000139, 'Sao Tome and Principe', 0, 0, 'ST');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000140, 'Saudi Arabia', 0, 0, 'SA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000141, 'Senegal', 0, 0, 'SN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000142, 'Seychelles', 0, 0, 'SC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000143, 'Sierra Leone', 0, 0, 'SL');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000144, 'Singapore', 0, 0, 'SG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000145, 'Slovakia', 0, 0, 'SK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000146, 'Slovenia', 0, 0, 'SI');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000147, 'Solomon Is', 0, 0, 'SB');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000148, 'Somali', 0, 0, 'SO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000149, 'South Africa', 0, 0, 'ZA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000150, 'Spain', 0, 0, 'ES');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000151, 'Sri Lanka', 0, 0, 'LK');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000152, 'St.Lucia', 0, 0, 'LC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000153, 'St.Vincent', 0, 0, 'VC');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000154, 'Sudan', 0, 0, 'SD');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000155, 'Suriname', 0, 0, 'SR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000156, 'Swaziland', 0, 0, 'SZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000157, 'Sweden', 0, 0, 'SE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000158, 'Switzerland', 0, 0, 'CH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000159, 'Syria', 0, 0, 'SY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000160, 'Taiwan', 0, 0, 'TW');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000161, 'Tajikstan', 0, 0, 'TJ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000162, 'Tanzania', 0, 0, 'TZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000163, 'Thailand', 0, 0, 'TH');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000164, 'Togo', 0, 0, 'TG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000165, 'Tonga', 0, 0, 'TO');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000166, 'Trinidad and Tobago', 0, 0, 'TT');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000167, 'Tunisia', 0, 0, 'TN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000168, 'Turkey', 0, 0, 'TR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000169, 'Turkmenistan', 0, 0, 'TM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000170, 'Uganda', 0, 0, 'UG');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000171, 'Ukraine', 0, 0, 'UA');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000172, 'United Arab Emirates', 0, 0, 'AE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000173, 'United Kiongdom', 0, 0, 'GB');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000174, 'United States of America', 0, 0, 'US');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000175, 'Uruguay', 0, 0, 'UY');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000176, 'Uzbekistan', 0, 0, 'UZ');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000177, 'Venezuela', 0, 0, 'VE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000178, 'Vietnam', 0, 0, 'VN');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000179, 'Yemen', 0, 0, 'YE');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000180, 'Yugoslavia', 0, 0, 'YU');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000181, 'Zimbabwe', 0, 0, 'ZW');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000182, 'Zaire', 0, 0, 'ZR');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (1000183, 'Zambia', 0, 0, 'ZM');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (110000, '北京市', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (120000, '天津市', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (130000, '河北省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (140000, '山西省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (150000, '内蒙古自治区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (210000, '辽宁省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (220000, '吉林省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (230000, '黑龙江省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (310000, '上海市', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (320000, '江苏省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (330000, '浙江省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (340000, '安徽省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (350000, '福建省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (360000, '江西省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (370000, '山东省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (410000, '河南省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (420000, '湖北省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (430000, '湖南省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (440000, '广东省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (450000, '广西壮族自治区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (460000, '海南省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (500000, '重庆市', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (510000, '四川省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (520000, '贵州省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (530000, '云南省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (540000, '西藏自治区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (610000, '陕西省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (620000, '甘肃省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (630000, '青海省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (640000, '宁夏回族自治区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (650000, '新疆维吾尔自治区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (710000, '台湾省', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (810000, '香港特别行政区', 1000035, 0, '');
INSERT INTO t_zone (code, name, parent_id, sort_id, remark) VALUES (820000, '澳门特别行政区', 1000035, 0, '');


-- auto-generated definition
CREATE TABLE t_zone(
  id  BIGINT(19) AUTO_INCREMENT COMMENT '主键' PRIMARY KEY,
  code      INT(6)                  NOT NULL
  COMMENT '地区编码',
  name      VARCHAR(255)            NULL
  COMMENT '地区名称',
  parent_id BIGINT(19) DEFAULT '0'  NOT NULL
  COMMENT '父级code',
  sort_id   INT DEFAULT '0'         NULL
  COMMENT '排序',
  remark    VARCHAR(100) DEFAULT '' NULL
  COMMENT '备注'
) CHARSET 'utf8' COMMENT '地区信息表';
