package com.hsy.cms.better.mapper;

import com.hsy.cms.better.bean.entity.TCmsCheck;
import com.hsy.cms.better.bean.entity.TCmsCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCmsCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    long countByExample(TCmsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int deleteByExample(TCmsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int insert(TCmsCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int insertSelective(TCmsCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    List<TCmsCheck> selectByExample(TCmsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    TCmsCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCmsCheck record, @Param("example") TCmsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCmsCheck record, @Param("example") TCmsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCmsCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCmsCheck record);
}