package com.hsy.cms.better.mapper;

import com.hsy.cms.better.bean.entity.TCmsInformation;
import com.hsy.cms.better.bean.entity.TCmsInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCmsInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    long countByExample(TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int deleteByExample(TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int insert(TCmsInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int insertSelective(TCmsInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    List<TCmsInformation> selectByExampleWithBLOBs(TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    List<TCmsInformation> selectByExample(TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    TCmsInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCmsInformation record, @Param("example") TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TCmsInformation record, @Param("example") TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCmsInformation record, @Param("example") TCmsInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCmsInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TCmsInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cms_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCmsInformation record);
}