package com.hsy.cms.better.mapper;

import com.hsy.cms.better.bean.entity.TCrmUser;
import com.hsy.cms.better.bean.entity.TCrmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCrmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    long countByExample(TCrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int deleteByExample(TCrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int insert(TCrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int insertSelective(TCrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    List<TCrmUser> selectByExample(TCrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    TCrmUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCrmUser record, @Param("example") TCrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCrmUser record, @Param("example") TCrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCrmUser record);
}