package com.hsy.cms.better.mapper;

import com.hsy.cms.better.bean.entity.TCrmRolePermission;
import com.hsy.cms.better.bean.entity.TCrmRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCrmRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    long countByExample(TCrmRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(TCrmRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int insert(TCrmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(TCrmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    List<TCrmRolePermission> selectByExample(TCrmRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    TCrmRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCrmRolePermission record, @Param("example") TCrmRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCrmRolePermission record, @Param("example") TCrmRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCrmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCrmRolePermission record);
}