package com.hsy.cms.better.mapper;

import com.hsy.cms.better.bean.entity.TCrmRole;
import com.hsy.cms.better.bean.entity.TCrmRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCrmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    long countByExample(TCrmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int deleteByExample(TCrmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int insert(TCrmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int insertSelective(TCrmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    List<TCrmRole> selectByExample(TCrmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    TCrmRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCrmRole record, @Param("example") TCrmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCrmRole record, @Param("example") TCrmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCrmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCrmRole record);
}