package com.hsy.cms.better.bean.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   资讯类别表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cms_dict
 */
public class TCmsDict {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   字典唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.dict_id
     *
     * @mbg.generated
     */
    private String dictId;

    /**
     * Database Column Remarks:
     *   字典类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.dict_name
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     * Database Column Remarks:
     *   父级唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建者用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   更新者用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_dict.del
     *
     * @mbg.generated
     */
    private byte[] del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.id
     *
     * @return the value of t_cms_dict.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.id
     *
     * @param id the value for t_cms_dict.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.dict_id
     *
     * @return the value of t_cms_dict.dict_id
     *
     * @mbg.generated
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.dict_id
     *
     * @param dictId the value for t_cms_dict.dict_id
     *
     * @mbg.generated
     */
    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.dict_name
     *
     * @return the value of t_cms_dict.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.dict_name
     *
     * @param dictName the value for t_cms_dict.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.parent_id
     *
     * @return the value of t_cms_dict.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.parent_id
     *
     * @param parentId the value for t_cms_dict.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.create_time
     *
     * @return the value of t_cms_dict.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.create_time
     *
     * @param createTime the value for t_cms_dict.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.create_user_id
     *
     * @return the value of t_cms_dict.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.create_user_id
     *
     * @param createUserId the value for t_cms_dict.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.update_time
     *
     * @return the value of t_cms_dict.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.update_time
     *
     * @param updateTime the value for t_cms_dict.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.update_user_id
     *
     * @return the value of t_cms_dict.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.update_user_id
     *
     * @param updateUserId the value for t_cms_dict.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_dict.del
     *
     * @return the value of t_cms_dict.del
     *
     * @mbg.generated
     */
    public byte[] getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_dict.del
     *
     * @param del the value for t_cms_dict.del
     *
     * @mbg.generated
     */
    public void setDel(byte[] del) {
        this.del = del;
    }
}