package com.hsy.cms.better.bean.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   新闻咨询表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cms_information
 */
public class TCmsInformation {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   新闻标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   大标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.big_title
     *
     * @mbg.generated
     */
    private String bigTitle;

    /**
     * Database Column Remarks:
     *   新闻简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   新闻种类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.category
     *
     * @mbg.generated
     */
    private Integer category;

    /**
     * Database Column Remarks:
     *   新闻图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.picture_id
     *
     * @mbg.generated
     */
    private String pictureId;

    /**
     * Database Column Remarks:
     *   审核id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.check_id
     *
     * @mbg.generated
     */
    private String checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   创建者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   更新者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * Database Column Remarks:
     *   1，正常 2，删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.del
     *
     * @mbg.generated
     */
    private Integer del;

    /**
     * Database Column Remarks:
     *   浏览数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.browses_count
     *
     * @mbg.generated
     */
    private Integer browsesCount;

    /**
     * Database Column Remarks:
     *   喜欢数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.likes_count
     *
     * @mbg.generated
     */
    private Integer likesCount;

    /**
     * Database Column Remarks:
     *   回复数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.comments_count
     *
     * @mbg.generated
     */
    private Integer commentsCount;

    /**
     * Database Column Remarks:
     *   是否允许评论 0:允许 1:不允许
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.allow_comment
     *
     * @mbg.generated
     */
    private byte[] allowComment;

    /**
     * Database Column Remarks:
     *   评论开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.comment_start_time
     *
     * @mbg.generated
     */
    private Date commentStartTime;

    /**
     * Database Column Remarks:
     *   评论结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.comment_end_time
     *
     * @mbg.generated
     */
    private Date commentEndTime;

    /**
     * Database Column Remarks:
     *   排序字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   栏目类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.classified_column
     *
     * @mbg.generated
     */
    private String classifiedColumn;

    /**
     * Database Column Remarks:
     *   文章作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   文章来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_information.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.id
     *
     * @return the value of t_cms_information.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.id
     *
     * @param id the value for t_cms_information.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.title
     *
     * @return the value of t_cms_information.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.title
     *
     * @param title the value for t_cms_information.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.big_title
     *
     * @return the value of t_cms_information.big_title
     *
     * @mbg.generated
     */
    public String getBigTitle() {
        return bigTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.big_title
     *
     * @param bigTitle the value for t_cms_information.big_title
     *
     * @mbg.generated
     */
    public void setBigTitle(String bigTitle) {
        this.bigTitle = bigTitle == null ? null : bigTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.description
     *
     * @return the value of t_cms_information.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.description
     *
     * @param description the value for t_cms_information.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.category
     *
     * @return the value of t_cms_information.category
     *
     * @mbg.generated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.category
     *
     * @param category the value for t_cms_information.category
     *
     * @mbg.generated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.picture_id
     *
     * @return the value of t_cms_information.picture_id
     *
     * @mbg.generated
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.picture_id
     *
     * @param pictureId the value for t_cms_information.picture_id
     *
     * @mbg.generated
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.check_id
     *
     * @return the value of t_cms_information.check_id
     *
     * @mbg.generated
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.check_id
     *
     * @param checkId the value for t_cms_information.check_id
     *
     * @mbg.generated
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.create_date
     *
     * @return the value of t_cms_information.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.create_date
     *
     * @param createDate the value for t_cms_information.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.update_date
     *
     * @return the value of t_cms_information.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.update_date
     *
     * @param updateDate the value for t_cms_information.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.create_user_id
     *
     * @return the value of t_cms_information.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.create_user_id
     *
     * @param createUserId the value for t_cms_information.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.update_user_id
     *
     * @return the value of t_cms_information.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.update_user_id
     *
     * @param updateUserId the value for t_cms_information.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.del
     *
     * @return the value of t_cms_information.del
     *
     * @mbg.generated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.del
     *
     * @param del the value for t_cms_information.del
     *
     * @mbg.generated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.browses_count
     *
     * @return the value of t_cms_information.browses_count
     *
     * @mbg.generated
     */
    public Integer getBrowsesCount() {
        return browsesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.browses_count
     *
     * @param browsesCount the value for t_cms_information.browses_count
     *
     * @mbg.generated
     */
    public void setBrowsesCount(Integer browsesCount) {
        this.browsesCount = browsesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.likes_count
     *
     * @return the value of t_cms_information.likes_count
     *
     * @mbg.generated
     */
    public Integer getLikesCount() {
        return likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.likes_count
     *
     * @param likesCount the value for t_cms_information.likes_count
     *
     * @mbg.generated
     */
    public void setLikesCount(Integer likesCount) {
        this.likesCount = likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.comments_count
     *
     * @return the value of t_cms_information.comments_count
     *
     * @mbg.generated
     */
    public Integer getCommentsCount() {
        return commentsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.comments_count
     *
     * @param commentsCount the value for t_cms_information.comments_count
     *
     * @mbg.generated
     */
    public void setCommentsCount(Integer commentsCount) {
        this.commentsCount = commentsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.allow_comment
     *
     * @return the value of t_cms_information.allow_comment
     *
     * @mbg.generated
     */
    public byte[] getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.allow_comment
     *
     * @param allowComment the value for t_cms_information.allow_comment
     *
     * @mbg.generated
     */
    public void setAllowComment(byte[] allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.comment_start_time
     *
     * @return the value of t_cms_information.comment_start_time
     *
     * @mbg.generated
     */
    public Date getCommentStartTime() {
        return commentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.comment_start_time
     *
     * @param commentStartTime the value for t_cms_information.comment_start_time
     *
     * @mbg.generated
     */
    public void setCommentStartTime(Date commentStartTime) {
        this.commentStartTime = commentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.comment_end_time
     *
     * @return the value of t_cms_information.comment_end_time
     *
     * @mbg.generated
     */
    public Date getCommentEndTime() {
        return commentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.comment_end_time
     *
     * @param commentEndTime the value for t_cms_information.comment_end_time
     *
     * @mbg.generated
     */
    public void setCommentEndTime(Date commentEndTime) {
        this.commentEndTime = commentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.sort
     *
     * @return the value of t_cms_information.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.sort
     *
     * @param sort the value for t_cms_information.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.keywords
     *
     * @return the value of t_cms_information.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.keywords
     *
     * @param keywords the value for t_cms_information.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.classified_column
     *
     * @return the value of t_cms_information.classified_column
     *
     * @mbg.generated
     */
    public String getClassifiedColumn() {
        return classifiedColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.classified_column
     *
     * @param classifiedColumn the value for t_cms_information.classified_column
     *
     * @mbg.generated
     */
    public void setClassifiedColumn(String classifiedColumn) {
        this.classifiedColumn = classifiedColumn == null ? null : classifiedColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.author
     *
     * @return the value of t_cms_information.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.author
     *
     * @param author the value for t_cms_information.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.source
     *
     * @return the value of t_cms_information.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.source
     *
     * @param source the value for t_cms_information.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_information.content
     *
     * @return the value of t_cms_information.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_information.content
     *
     * @param content the value for t_cms_information.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}