package com.hsy.cms.better.bean.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   审核表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cms_check
 */
public class TCmsCheck {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   审核唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_id
     *
     * @mbg.generated
     */
    private String checkId;

    /**
     * Database Column Remarks:
     *   审核单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_name
     *
     * @mbg.generated
     */
    private String checkName;

    /**
     * Database Column Remarks:
     *   审核状态：0:未审核 1：审核中 2：审核通过 3：审核失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_state
     *
     * @mbg.generated
     */
    private byte[] checkState;

    /**
     * Database Column Remarks:
     *   审核备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_remark
     *
     * @mbg.generated
     */
    private String checkRemark;

    /**
     * Database Column Remarks:
     *   是否删除：0未删除 1：已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.del
     *
     * @mbg.generated
     */
    private byte[] del;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_time
     *
     * @mbg.generated
     */
    private Date checkTime;

    /**
     * Database Column Remarks:
     *   审核者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cms_check.check_user_id
     *
     * @mbg.generated
     */
    private String checkUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.id
     *
     * @return the value of t_cms_check.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.id
     *
     * @param id the value for t_cms_check.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_id
     *
     * @return the value of t_cms_check.check_id
     *
     * @mbg.generated
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_id
     *
     * @param checkId the value for t_cms_check.check_id
     *
     * @mbg.generated
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_name
     *
     * @return the value of t_cms_check.check_name
     *
     * @mbg.generated
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_name
     *
     * @param checkName the value for t_cms_check.check_name
     *
     * @mbg.generated
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName == null ? null : checkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_state
     *
     * @return the value of t_cms_check.check_state
     *
     * @mbg.generated
     */
    public byte[] getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_state
     *
     * @param checkState the value for t_cms_check.check_state
     *
     * @mbg.generated
     */
    public void setCheckState(byte[] checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_remark
     *
     * @return the value of t_cms_check.check_remark
     *
     * @mbg.generated
     */
    public String getCheckRemark() {
        return checkRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_remark
     *
     * @param checkRemark the value for t_cms_check.check_remark
     *
     * @mbg.generated
     */
    public void setCheckRemark(String checkRemark) {
        this.checkRemark = checkRemark == null ? null : checkRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.del
     *
     * @return the value of t_cms_check.del
     *
     * @mbg.generated
     */
    public byte[] getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.del
     *
     * @param del the value for t_cms_check.del
     *
     * @mbg.generated
     */
    public void setDel(byte[] del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.create_time
     *
     * @return the value of t_cms_check.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.create_time
     *
     * @param createTime the value for t_cms_check.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.create_user_id
     *
     * @return the value of t_cms_check.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.create_user_id
     *
     * @param createUserId the value for t_cms_check.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_time
     *
     * @return the value of t_cms_check.check_time
     *
     * @mbg.generated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_time
     *
     * @param checkTime the value for t_cms_check.check_time
     *
     * @mbg.generated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cms_check.check_user_id
     *
     * @return the value of t_cms_check.check_user_id
     *
     * @mbg.generated
     */
    public String getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cms_check.check_user_id
     *
     * @param checkUserId the value for t_cms_check.check_user_id
     *
     * @mbg.generated
     */
    public void setCheckUserId(String checkUserId) {
        this.checkUserId = checkUserId == null ? null : checkUserId.trim();
    }
}