package com.hsy.cms.better.bean.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_crm_permission
 */
public class TCrmPermission {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.auth_address
     *
     * @mbg.generated
     */
    private String authAddress;

    /**
     * Database Column Remarks:
     *   权限描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.auth_description
     *
     * @mbg.generated
     */
    private String authDescription;

    /**
     * Database Column Remarks:
     *   父级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   权限类型：BUTTON:按钮 MENU:菜单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.auth_type
     *
     * @mbg.generated
     */
    private String authType;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.creater
     *
     * @mbg.generated
     */
    private Long creater;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.updater
     *
     * @mbg.generated
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_permission.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.id
     *
     * @return the value of t_crm_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.id
     *
     * @param id the value for t_crm_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.auth_address
     *
     * @return the value of t_crm_permission.auth_address
     *
     * @mbg.generated
     */
    public String getAuthAddress() {
        return authAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.auth_address
     *
     * @param authAddress the value for t_crm_permission.auth_address
     *
     * @mbg.generated
     */
    public void setAuthAddress(String authAddress) {
        this.authAddress = authAddress == null ? null : authAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.auth_description
     *
     * @return the value of t_crm_permission.auth_description
     *
     * @mbg.generated
     */
    public String getAuthDescription() {
        return authDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.auth_description
     *
     * @param authDescription the value for t_crm_permission.auth_description
     *
     * @mbg.generated
     */
    public void setAuthDescription(String authDescription) {
        this.authDescription = authDescription == null ? null : authDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.parent_id
     *
     * @return the value of t_crm_permission.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.parent_id
     *
     * @param parentId the value for t_crm_permission.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.auth_type
     *
     * @return the value of t_crm_permission.auth_type
     *
     * @mbg.generated
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.auth_type
     *
     * @param authType the value for t_crm_permission.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(String authType) {
        this.authType = authType == null ? null : authType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.creater
     *
     * @return the value of t_crm_permission.creater
     *
     * @mbg.generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.creater
     *
     * @param creater the value for t_crm_permission.creater
     *
     * @mbg.generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.create_time
     *
     * @return the value of t_crm_permission.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.create_time
     *
     * @param createTime the value for t_crm_permission.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.updater
     *
     * @return the value of t_crm_permission.updater
     *
     * @mbg.generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.updater
     *
     * @param updater the value for t_crm_permission.updater
     *
     * @mbg.generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_permission.update_time
     *
     * @return the value of t_crm_permission.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_permission.update_time
     *
     * @param updateTime the value for t_crm_permission.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}