package com.hsy.cms.better.bean.entity;

/**
 * Database Table Remarks:
 *   用户角色表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_crm_user_role
 */
public class TCrmUserRole {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_user_role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   关联用户表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_user_role.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   关联角色表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_user_role.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_user_role.id
     *
     * @return the value of t_crm_user_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_user_role.id
     *
     * @param id the value for t_crm_user_role.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_user_role.user_id
     *
     * @return the value of t_crm_user_role.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_user_role.user_id
     *
     * @param userId the value for t_crm_user_role.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_user_role.role_id
     *
     * @return the value of t_crm_user_role.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_user_role.role_id
     *
     * @param roleId the value for t_crm_user_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}