package com.hsy.cms.better.bean.entity;

/**
 * Database Table Remarks:
 *   角色权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_crm_role_permission
 */
public class TCrmRolePermission {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_role_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   关联角色表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_role_permission.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   关联角色表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_crm_role_permission.permission_id
     *
     * @mbg.generated
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_role_permission.id
     *
     * @return the value of t_crm_role_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_role_permission.id
     *
     * @param id the value for t_crm_role_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_role_permission.role_id
     *
     * @return the value of t_crm_role_permission.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_role_permission.role_id
     *
     * @param roleId the value for t_crm_role_permission.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_crm_role_permission.permission_id
     *
     * @return the value of t_crm_role_permission.permission_id
     *
     * @mbg.generated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_crm_role_permission.permission_id
     *
     * @param permissionId the value for t_crm_role_permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}