spring:
  datasource:
    url: jdbc:mariadb://172.16.191.102:3306/cms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false # 实时展示页面内容