server:
  port: 8080
  session:
    timeout: 10 # 用户会话 session过期时间，以秒为单位
spring:
  datasource:
    url: jdbc:mysql://192.168.216.129:3306/cms_simple?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb

mybatis:
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    org:
      springfremework:
        web: debug
      apache:
        ibatis: TRACE
    java:
      sql:
        Connection: DEBUG
        Statement: DEBUG
        PreparedStatement: DEBUG