spring:
  datasource:
    url: jdbc:mysql://172.16.191.102:3306/cms_simple?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
    encoding:
      charset: UTF-8
      force: true

mybatis:
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    org:
      springfremework:
        web: debug
      apache:
        ibatis: TRACE
    java:
      sql:
        Connection: DEBUG
        Statement: DEBUG
        PreparedStatement: DEBUG

